/**
 * Gateway Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import { convertToType } from '../../shared';





/**
* The Strategy model module.
* @module model/Strategy
* @version 1.0.0
*/
export default class Strategy {
    /**
    * Constructs a new <code>Strategy</code>.
    * @alias module:model/Strategy
    * @class
    * @param id {String} 
    * @param name {String} 
    * @param description {String} 
    * @param createdTime {Date} 
    * @param isActive {Boolean} 
    * @param granularity {module:model/Strategy.GranularityEnum} 
    * @param postedBy {String} 
    */

    constructor(id, name, description, createdTime, isActive, granularity, postedBy) {





        this['id'] = id; this['name'] = name; this['description'] = description; this['createdTime'] = createdTime; this['isActive'] = isActive; this['granularity'] = granularity; this['postedBy'] = postedBy;


    }

    /**
    * Constructs a <code>Strategy</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Strategy} obj Optional instance to populate.
    * @return {module:model/Strategy} The populated <code>Strategy</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Strategy();





            if (data.hasOwnProperty('id')) {
                obj['id'] = convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('createdTime')) {
                obj['createdTime'] = convertToType(data['createdTime'], 'Date');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = convertToType(data['isActive'], 'Boolean');
            }
            if (data.hasOwnProperty('granularity')) {
                obj['granularity'] = convertToType(data['granularity'], 'String');
            }
            if (data.hasOwnProperty('postedBy')) {
                obj['postedBy'] = convertToType(data['postedBy'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Date} createdTime
    */
    createdTime = undefined;
    /**
    * @member {Boolean} isActive
    */
    isActive = undefined;
    /**
    * @member {module:model/Strategy.GranularityEnum} granularity
    */
    granularity = undefined;
    /**
    * @member {String} postedBy
    */
    postedBy = undefined;






    /**
    * Allowed values for the <code>granularity</code> property.
    * @enum {String}
    * @readonly
    */
    static GranularityEnum = {

        /**
         * value: "M5"
         * @const
         */
        "M5": "M5",

        /**
         * value: "M15"
         * @const
         */
        "M15": "M15",

        /**
         * value: "M30"
         * @const
         */
        "M30": "M30",

        /**
         * value: "H1"
         * @const
         */
        "H1": "H1",

        /**
         * value: "H4"
         * @const
         */
        "H4": "H4",

        /**
         * value: "D1"
         * @const
         */
        "D1": "D1"
    };



}


